//  $Header$
//  $Name$

package org.jax.mgi.dbs.mgd;

import java.util.Vector;

import org.jax.mgi.dbs.SchemaConstants;
import org.jax.mgi.dbs.mgd.dao.ACC_AccessionState;
import org.jax.mgi.shr.config.ConfigException;
import org.jax.mgi.shr.dbutils.DBException;
import org.jax.mgi.shr.dbutils.ResultsNavigator;
import org.jax.mgi.shr.dbutils.RowReference;
import org.jax.mgi.shr.dbutils.SQLDataManager;
import org.jax.mgi.shr.dbutils.SQLDataManagerFactory;
import org.jax.mgi.shr.dbutils.dao.SQLStream;
import org.jax.mgi.dbs.mgd.dao.ACC_AccessionDAO;
import org.jax.mgi.dbs.mgd.dao.ACC_AccessionState;
import org.jax.mgi.dbs.mgd.dao.ACC_AccessionKey;
import org.jax.mgi.dbs.mgd.dao.ACC_AccessionReferenceDAO;
import org.jax.mgi.dbs.mgd.dao.ACC_AccessionReferenceState;
import org.jax.mgi.dbs.mgd.MGITypeConstants;
import org.jax.mgi.dbs.mgd.LogicalDBConstants;


/**
 * @is An object that knows how to perform various function pertaining to
 *     accession IDs.
 * @has Nothing
 * @does
 *   <UL>
 *   <LI> Provides methods for handling accession IDs.
 *   </UL>
 * @company The Jackson Laboratory
 * @author dbm
 * @version 1.0
 */

public class AccessionLib
{
    /////////////////
    //  Variables  //
    /////////////////

    // The last number returned by each get() method.
    //
    public static int lastNumericMGI = 0;
    public static int lastNumericJ = 0;

    // constants for preferred bit
    public static final int PREFERRED = 1;
    public static final int NO_PREFERRED = 0;

    private static ACC_AccessionState accessionState =
        new ACC_AccessionState();
    private static ACC_AccessionReferenceState refState =
            new ACC_AccessionReferenceState();

    /**
     * Get the next available MGI ID.
     * @assumes Nothing
     * @effects Nothing
     * @return The next available MGI ID.
     * @throws ConfigException
     * @throws DBException
     */
    public static String getNextMGIID ()
        throws ConfigException, DBException
    {
        if (lastNumericMGI == 0)
        {
            String sql = "SELECT maxNumericPart " +
                         "FROM ACC_AccessionMax " +
                         "WHERE prefixPart = 'MGI:'";
            SQLDataManager sqlMgr =
                SQLDataManagerFactory.getShared(SchemaConstants.MGD);
            ResultsNavigator rn = sqlMgr.executeQuery(sql);
            rn.next();
            RowReference row = (RowReference)rn.getCurrent();
            lastNumericMGI = row.getInt(1).intValue();
        }
        lastNumericMGI++;

        return new String("MGI:"+lastNumericMGI);
    }


    /**
     * Get the next available J-Number.
     * @assumes Nothing
     * @effects Nothing
     * @return The next available J-Number.
     * @throws ConfigException
     * @throws DBException
     */
    public static String getNextJNum ()
        throws ConfigException, DBException
    {
        if (lastNumericJ == 0)
        {
            String sql = "SELECT maxNumericPart " +
                         "FROM ACC_AccessionMax " +
                         "WHERE prefixPart = 'J:'";
            SQLDataManager sqlMgr =
                SQLDataManagerFactory.getShared(SchemaConstants.MGD);
            ResultsNavigator rn = sqlMgr.executeQuery(sql);
            rn.next();
            RowReference row = (RowReference)rn.getCurrent();
            lastNumericJ = row.getInt(1).intValue();
        }
        lastNumericJ++;

        return new String("J:"+lastNumericJ);
    }


    /**
     * Get an ACC_AccessionState object that contains the next available MGI ID.
     * @assumes Nothing
     * @effects Nothing
     * @return The next available J-Number.
     * @throws ConfigException
     * @throws DBException
     */
    public static ACC_AccessionState getNextAccState ()
        throws ConfigException, DBException
    {
        ACC_AccessionState accState = new ACC_AccessionState();
        accState.setAccID(getNextMGIID());
        return accState;
    }


    /**
     * Update the ACC_AccessionMax table with new max values to account for
     * any accession IDs generated by this class.
     * @assumes Nothing
     * @effects Nothing
     * @return Nothing
     * @throws ConfigException
     * @throws DBException
     */
    public static void commitAccessionMax ()
        throws ConfigException, DBException
    {
        if (lastNumericMGI != 0)
        {
            String sql = "UPDATE ACC_AccessionMax " +
                         "SET maxNumericPart = " + lastNumericMGI + " " +
                         "WHERE prefixPart = 'MGI:'";
            SQLDataManager sqlMgr =
                SQLDataManagerFactory.getShared(SchemaConstants.MGD);
            sqlMgr.executeUpdate(sql);
            lastNumericMGI = 0;
        }

        if (lastNumericJ != 0)
        {
            String sql = "UPDATE ACC_AccessionMax " +
                         "SET maxNumericPart = " + lastNumericJ + " " +
                         "WHERE prefixPart = 'J:'";
            SQLDataManager sqlMgr =
                SQLDataManagerFactory.getShared(SchemaConstants.MGD);
            sqlMgr.executeUpdate(sql);
            lastNumericJ = 0;
        }
    }


    /**
     * Split an accession ID into its prefix and numeric parts.
     * @assumes Nothing
     * @effects Nothing
     * @param accID The accession ID to be split
     * @return A vector containing the prefix part (String) and numeric
     *         part (Integer) of the accession ID.
     */
    public static Vector splitAccID (String accID)
    {
        String prefixPart = null;
        Integer numericPart = null;
        Vector v = new Vector();

        // Return null prefix and numeric parts if the accession ID is
        // null or blank.
        //
        if (accID == null || accID.length() == 0)
        {
            v.add(prefixPart);
            v.add(numericPart);
            return v;
        }

        // Determine if the accession ID contains any characters prior to a
        // series of digits that ends the string.
        //
        String[] parts = accID.split("\\d*$");

        // If there is a prefix part, save it and set the numeric part to
        // be any remaining characters.  Otherwise, the entire accession ID
        // is the numeric part.
        //
        if (parts.length > 0)
        {
            prefixPart = parts[0];
            if (accID.length() > prefixPart.length())
                numericPart = Integer.valueOf(accID.substring(prefixPart.length()));

        }
        else
            numericPart = Integer.valueOf(accID);

        // Add the prefix and numeric parts to the vector and return it.
        //
        v.add(prefixPart);
        v.add(numericPart);
        return v;
    }

    /**
     * Puts the required DAO objects onto the given SQLStream
     * for creating a new association in the ACC_Accession between
     * a marker and the given accid and logicaldb and includes a 
     * a new ACC_ACCessionReference record for the given refs key
     * @assumes private attribute in ACC_ACCession will be false
     * and preferred attribute will be true
     * @effects DAO instances will be placed onto the SQLStream for
     * ACC_Accession and ACC_AccessionReference
     * @param logicalDB the logicaldb of the new association
     * @param accid the accession id of the new association
     * @param markerKey the marker key to associate to
     * @param refskey the refs key for ACC_AccessionReference
     * @param sqlStream the given SQLStream to place DAO objects onto
     */
    public static void createMarkerAssociation(Integer logicalDB, String accid,
                                         Integer markerKey, Integer refskey,
                                         SQLStream sqlStream)
    throws DBException, ConfigException
    {
        //ACC_AccessionState accessionState = new ACC_AccessionState();
        accessionState.clear();
        accessionState.setAccID(accid);
        accessionState.setLogicalDBKey(logicalDB);
        accessionState.setMGITypeKey(new Integer(MGITypeConstants.MARKER));
        Vector v = AccessionLib.splitAccID(accid);
        accessionState.setPrefixPart((String)v.get(0));
        accessionState.setNumericPart((Integer)v.get(1));
        accessionState.setObjectKey(markerKey);
        accessionState.setPrivateVal(new Boolean(false));
        accessionState.setPreferred(new Boolean(true));
        ACC_AccessionKey accessionKey = new ACC_AccessionKey();
        ACC_AccessionDAO accessionDAO =
            new ACC_AccessionDAO(accessionKey, accessionState);

        //ACC_AccessionReferenceState refState =
            //new ACC_AccessionReferenceState();
        refState.clear();
        refState.setAccessionKey(accessionKey.getKey());
        refState.setRefsKey(refskey);
        ACC_AccessionReferenceDAO refDAO =
            new ACC_AccessionReferenceDAO(refState);

        sqlStream.insert(accessionDAO);
        sqlStream.insert(refDAO);
    }

}


//  $Log$
//  Revision 1.4  2005/08/05 17:51:26  mbw
//  merged code from branch lib_java_dbsmgd-tr6046-1
//
//  Revision 1.3.14.1  2005/08/02 17:48:24  mbw
//  added new method for creating new accession associations to markers in the
//  ACC_Accession table
//
//  Revision 1.3  2004/07/28 18:43:23  mbw
//  javadocs only
//
//  Revision 1.2  2004/02/04 19:41:27  mbw
//  merged jsam branch to the trunk
//
//  Revision 1.1.2.1  2003/11/13 20:36:57  sc
//  PREFERRED, NOT_PREFERRED constans
//
//  Revision 1.1  2003/10/21 13:25:45  dbm
//  Initial version
//
//
/**************************************************************************
*
* Warranty Disclaimer and Copyright Notice
*
*  THE JACKSON LABORATORY MAKES NO REPRESENTATION ABOUT THE SUITABILITY OR
*  ACCURACY OF THIS SOFTWARE OR DATA FOR ANY PURPOSE, AND MAKES NO WARRANTIES,
*  EITHER EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY AND FITNESS FOR A
*  PARTICULAR PURPOSE OR THAT THE USE OF THIS SOFTWARE OR DATA WILL NOT
*  INFRINGE ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS, OR OTHER RIGHTS.
*  THE SOFTWARE AND DATA ARE PROVIDED "AS IS".
*
*  This software and data are provided to enhance knowledge and encourage
*  progress in the scientific community and are to be used only for research
*  and educational purposes.  Any reproduction or use for commercial purpose
*  is prohibited without the prior express written permission of The Jackson
*  Laboratory.
*
* Copyright \251 1996, 1999, 2002, 2003 by The Jackson Laboratory
*
* All Rights Reserved
*
**************************************************************************/
